import { useEffect, useMemo, useState } from "react";
import type { MouseEvent } from "react";
import { ArrowSquareOut, ArrowsClockwise, ChartBar, CheckCircle, CircleNotch, GearSix, House, Info, Key, Lightning, LockKeyOpen, Minus, Pulse, Stack, Timer, UsersThree, WarningCircle, X } from "@phosphor-icons/react";
import { normalizeSnapshot, type SnapshotEnvelope, usagePercent } from "./domain/snapshot";
import type { HostBridge } from "./bridge/host";
import { parseHostMessage, type HostMessage } from "./bridge/protocol";
import { Badge } from "./components/ui/badge";
import { Button } from "./components/ui/button";
import { Progress } from "./components/ui/progress";
import { Switch } from "./components/ui/switch";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./components/ui/tooltip";

type View = "overview" | "usage" | "plans" | "status" | "settings";
type BridgeState = "loading" | "auth-required" | "offline" | "error" | "live";
type AppProps = { bridge: HostBridge };

const views: Array<{ id: View; label: string; icon: typeof House }> = [
  { id: "overview", label: "Overview", icon: House }, { id: "usage", label: "Usage", icon: ChartBar }, { id: "plans", label: "Plans", icon: Stack }, { id: "status", label: "Status", icon: Pulse }, { id: "settings", label: "Settings", icon: GearSix },
];
const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value);
const integer = (value: number) => new Intl.NumberFormat("en-US", { maximumFractionDigits: 0 }).format(value);
const tokens = (value: number) => value >= 1e9 ? `${(value / 1e9).toFixed(2).replace(/\.00$/, "")}B` : value >= 1e6 ? `${(value / 1e6).toFixed(1).replace(/\.0$/, "")}M` : value >= 1e3 ? `${(value / 1e3).toFixed(1).replace(/\.0$/, "")}K` : integer(value);
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(value)) : "Not provided";

function SourceStrip({ state, capturedAt, onConnect }: { state: BridgeState; capturedAt?: string | null; onConnect: () => void }) {
  const live = state === "live";
  return <div className={`source-strip ${live ? "live" : "needs-auth"}`}><span className="source-mark">{live ? <CheckCircle weight="fill" /> : <LockKeyOpen weight="bold" />}</span><div><strong>{live ? "Live Cavoti session" : "Live session required"}</strong><span>{live ? `Updated ${date(capturedAt ?? null)}` : "Usage stays private until you connect a Cavoti browser session."}</span></div>{live ? <Badge variant="success">Connected</Badge> : <Button size="sm" variant="secondary" onClick={onConnect}>Connect Cavoti <ArrowSquareOut weight="bold" /></Button>}</div>;
}

function StatRail({ snapshot }: { snapshot: SnapshotEnvelope }) {
  return <div className="stat-rail"><div><span>Requests</span><strong>{integer(snapshot.stats.requests)}</strong></div><div><span>Total tokens</span><strong>{tokens(snapshot.stats.totalTokens)}</strong></div><div><span>Actual cost</span><strong>{money(snapshot.stats.actualCost)}</strong></div></div>;
}

function UsageMeter({ label, window, tone = "accent" }: { label: string; window: { used: number; limit: number }; tone?: string }) {
  const percent = usagePercent(window);
  return <div className="usage-meter"><div className="meter-label"><span>{label}</span><strong>{percent.toFixed(1)}%</strong></div><Progress value={percent} tone={tone === "good" ? "good" : "accent"} /><small>{money(window.used)} of {money(window.limit)}</small></div>;
}

function Overview({ snapshot, onNavigate }: { snapshot: SnapshotEnvelope; onNavigate: (view: View) => void }) {
  const plan = snapshot.subscriptions.find((item) => item.status === "active") ?? snapshot.subscriptions[0];
  const max = Math.max(...snapshot.dailyTrend.map((item) => item.requests), 1);
  return <div className="view-stack"><div className="view-heading"><div><span className="eyebrow">Live usage surface</span><h1>At a glance</h1></div><Button variant="ghost" size="icon" aria-label="Refresh snapshot" onClick={() => window.dispatchEvent(new CustomEvent("cavoti-refresh"))}><ArrowsClockwise weight="bold" /></Button></div><SourceStrip state="live" capturedAt={snapshot.capturedAt} onConnect={() => undefined} />{snapshot.banner ? <div className="signal-note"><Lightning weight="fill" /><div><strong>{snapshot.banner.title}</strong><span>{snapshot.banner.message}</span></div></div> : null}{plan ? <section className="primary-usage"><div className="section-top"><div><span className="eyebrow">Primary plan</span><h2>{plan.name}</h2></div><Badge variant="success">{plan.status}</Badge></div><div className="usage-columns"><UsageMeter label="Daily window" window={plan.usage.daily} /><UsageMeter label="Weekly window" window={plan.usage.weekly} tone="good" /><UsageMeter label="Monthly window" window={plan.usage.monthly} tone="good" /></div><div className="plan-foot"><span>{plan.billingKind}</span><span>Renews {date(plan.expiresAt)}</span></div></section> : <Empty title="No active plan" message="Cavoti did not return an active subscription for this session." />}{<StatRail snapshot={snapshot} />}<section className="split-grid"><div className="surface-section"><div className="section-top"><div><span className="eyebrow">Top models</span><h2>Where usage went</h2></div><Button variant="ghost" size="sm" onClick={() => onNavigate("usage")}>Details <ArrowSquareOut /></Button></div><ModelRows rows={snapshot.models.slice(0, 4)} /></div><div className="surface-section trend-section"><div className="section-top"><div><span className="eyebrow">Request rhythm</span><h2>Daily volume</h2></div><Pulse className="section-icon" /></div><div className="mini-bars">{snapshot.dailyTrend.map((item) => <span key={item.date} style={{ height: `${Math.max(8, (item.requests / max) * 100)}%` }} title={`${item.date}: ${integer(item.requests)} requests`} />)}</div><div className="trend-foot"><span>{snapshot.dailyTrend[0]?.date ?? ""}</span><span>{snapshot.dailyTrend.at(-1)?.date ?? ""}</span></div></div></section></div>;
}

function ModelRows({ rows }: { rows: Array<{ name: string; requests: number; tokens: number; actualCost: number }> }) { return rows.length ? <div className="model-rows">{rows.map((row) => <div className="model-row" key={row.name}><span><i className="model-dot" />{row.name}</span><strong>{money(row.actualCost)}</strong></div>)}</div> : <Empty title="No model detail" message="The connected session returned no model breakdown." compact />; }

function Usage({ snapshot }: { snapshot: SnapshotEnvelope }) {
  return <div className="view-stack"><div className="view-heading"><div><span className="eyebrow">Usage dashboard</span><h1>Usage</h1></div><Badge variant="outline">Live window</Badge></div><div className="filter-row"><div className="segmented" role="tablist" aria-label="Usage range"><button role="tab" aria-selected="true">7 days</button></div><Badge variant="outline">All traffic · captured window</Badge></div><StatRail snapshot={snapshot} /><div className="surface-section"><div className="section-top"><div><span className="eyebrow">By endpoint</span><h2>Cost centers</h2></div><span className="muted-label">actual cost</span></div><DataRows rows={snapshot.stats.endpoints} empty="No endpoint data returned." /></div><div className="surface-section"><div className="section-top"><div><span className="eyebrow">By group</span><h2>Billing groups</h2></div><UsersThree className="section-icon" /></div><DataRows rows={snapshot.groups} empty="No group data returned." /></div></div>;
}

function DataRows({ rows, empty }: { rows: Array<{ name: string; requests: number; tokens: number; actualCost: number }>; empty: string }) { return rows.length ? <div className="data-rows">{rows.map((row) => <div className="data-row" key={row.name}><span className="row-name">{row.name}</span><span>{integer(row.requests)} req</span><span>{tokens(row.tokens)}</span><strong>{money(row.actualCost)}</strong></div>)}</div> : <Empty title="No rows" message={empty} compact />; }

function Plans({ snapshot, onConnect }: { snapshot: SnapshotEnvelope; onConnect: () => void }) { return <div className="view-stack"><div className="view-heading"><div><span className="eyebrow">Entitlements</span><h1>Plans</h1></div><Button variant="outline" size="sm" onClick={onConnect}>Manage on Cavoti <ArrowSquareOut /></Button></div>{snapshot.subscriptions.length ? <div className="plan-list">{snapshot.subscriptions.map((plan, index) => <section className={`plan-row ${index === 0 ? "featured" : ""}`} key={`${plan.name}-${index}`}><div className="plan-head"><div><Badge variant={plan.status === "active" ? "success" : "outline"}>{plan.status}</Badge><h2>{plan.name}</h2></div><span className="plan-index">{String(index + 1).padStart(2, "0")}</span></div><div className="plan-meters"><UsageMeter label="Daily" window={plan.usage.daily} /><UsageMeter label="Weekly" window={plan.usage.weekly} tone="good" /><UsageMeter label="Monthly" window={plan.usage.monthly} tone="good" /></div><div className="plan-foot"><span>{plan.billingKind}</span><span>Renews {date(plan.expiresAt)}</span></div></section>)}</div> : <Empty title="No plan records" message="Connect Cavoti to read your current entitlements." onAction={onConnect} />}{snapshot.quotaResetCards.length ? <div className="signal-note"><Timer /><div><strong>Quota resets</strong><span>{snapshot.quotaResetCards.map((card) => `${card.label}${card.resetAt ? ` · ${date(card.resetAt)}` : ""}`).join(" · ")}</span></div></div> : null}</div>; }

function Status({ snapshot, state, onConnect }: { snapshot?: SnapshotEnvelope; state: BridgeState; onConnect: () => void }) { return <div className="view-stack"><div className="view-heading"><div><span className="eyebrow">Connection monitor</span><h1>Status</h1></div><Badge variant={state === "live" ? "success" : "warning"}>{state === "live" ? "Operational" : state}</Badge></div><div className="status-summary"><div className="status-orb">{state === "live" ? <CheckCircle weight="fill" /> : <WarningCircle weight="fill" />}</div><div><span className="eyebrow">Cavoti bridge</span><h2>{state === "live" ? "Live snapshot received" : "No live snapshot yet"}</h2><p>{state === "live" ? `Last received ${date(snapshot?.capturedAt ?? null)}.` : "The overlay never receives credentials. It only receives sanitized aggregate JSON from the authenticated browser profile."}</p></div></div>{snapshot ? <div className="check-list"><CheckRow label="Account record" value={snapshot.account.status} good /><CheckRow label="Plan records" value={`${snapshot.subscriptions.length} returned`} good={snapshot.subscriptions.length > 0} /><CheckRow label="Usage aggregates" value={`${snapshot.models.length} models · ${snapshot.stats.endpoints.length} endpoints`} good={snapshot.models.length > 0} /></div> : <Empty title="Live session required" message="Sign in through the Cavoti connection window to populate this view." onAction={onConnect} />}{snapshot?.announcements.length ? <div className="signal-note"><Info /><div><strong>{snapshot.announcements[0].title}</strong><span>{snapshot.announcements[0].message}</span></div></div> : null}</div>; }
function CheckRow({ label, value, good }: { label: string; value: string; good: boolean }) { return <div className="check-row"><span className={good ? "check-dot good" : "check-dot"}>{good ? <CheckCircle weight="fill" /> : <Info weight="regular" />}</span><span>{label}</span><strong>{value}</strong></div>; }

function Settings({ topmost, onTopmost, onClear, onConnect }: { topmost: boolean; onTopmost: (value: boolean) => void; onClear: () => void; onConnect: () => void }) { return <div className="view-stack"><div className="view-heading"><div><span className="eyebrow">Application</span><h1>Settings</h1></div><Badge variant="outline">Local</Badge></div><section className="surface-section settings-section"><span className="eyebrow">Window behavior</span><div className="setting-row"><div><strong>Keep on top</strong><small>Keep the popover above other windows.</small></div><Switch checked={topmost} onCheckedChange={onTopmost} aria-label="Keep on top" /></div><div className="setting-row"><div><strong>Connection profile</strong><small>Session cookies stay inside the WebView2 profile.</small></div><Button variant="outline" size="sm" onClick={onConnect}>Open sign in</Button></div></section><section className="surface-section settings-section"><span className="eyebrow">Privacy boundary</span><div className="privacy-note"><Key /><div><strong>Credentials never reach this UI</strong><small>Only normalized usage, plan, and account status data is forwarded.</small></div></div><Button variant="ghost" size="sm" onClick={onClear}>Clear local preferences</Button></section></div>; }

function Empty({ title, message, onAction, compact = false }: { title: string; message: string; onAction?: () => void; compact?: boolean }) { return <div className={`empty-state ${compact ? "compact" : ""}`}><img src="./cavoti-logo.png" alt="" /><div><strong>{title}</strong><p>{message}</p>{onAction ? <Button size="sm" variant="secondary" onClick={onAction}>Connect Cavoti <ArrowSquareOut /></Button> : null}</div></div>; }

export function App({ bridge }: AppProps) {
  const [state, setState] = useState<BridgeState>("loading");
  const [snapshot, setSnapshot] = useState<SnapshotEnvelope>();
  const [view, setView] = useState<View>("overview");
  const [topmost, setTopmost] = useState(true);
  const connect = () => bridge.post({ action: "connect" });
  useEffect(() => { const unsubscribe = bridge.subscribe((raw) => { const message = parseHostMessage(raw); if (!message) return; if (message.type === "snapshot") { const next = normalizeSnapshot(message.snapshot); if (next) { setSnapshot(next); setState("live"); if (message.settings) setTopmost(message.settings.topmost); } } else if (message.type === "settings") { setTopmost(message.settings.topmost); } else { setState(message.state); } }); bridge.post({ action: "bootstrap" }); const refresh = () => bridge.post({ action: "refresh" }); window.addEventListener("cavoti-refresh", refresh); return () => { unsubscribe(); window.removeEventListener("cavoti-refresh", refresh); }; }, [bridge]);
  const title = useMemo(() => views.find((item) => item.id === view)?.label ?? "Overview", [view]);
  const beginDrag = (event: MouseEvent<HTMLElement>) => { if (event.button !== 0 || (event.target as HTMLElement).closest("button")) return; bridge.post({ action: "drag" }); };
  return <TooltipProvider delayDuration={300}><div className="app-shell"><header className="titlebar" data-drag-region onMouseDown={beginDrag}><button className="brand-button" onClick={() => setView("overview")}><img src="./favicon.png" alt="Cavoti" /><span><strong>Cavoti</strong><small>{state === "live" ? "live usage" : "session bridge"}</small></span></button><div className="titlebar-status"><span className={`status-dot ${state === "live" ? "good" : "warning"}`} />{state === "live" ? "Connected" : "Not connected"}</div><div className="window-actions"><Button variant="ghost" size="icon" aria-label="Minimize window" onClick={() => bridge.post({ action: "minimize" })}><Minus /></Button><Button variant="ghost" size="icon" aria-label="Close window" onClick={() => bridge.post({ action: "close" })}><X /></Button></div></header><div className="shell-body"><nav className="nav-rail" aria-label="Primary navigation" role="tablist">{views.map(({ id, label, icon: Icon }) => <Tooltip key={id}><TooltipTrigger asChild><button role="tab" className={`nav-button ${view === id ? "active" : ""}`} aria-label={label} aria-selected={view === id} onClick={() => setView(id)}><Icon weight={view === id ? "fill" : "regular"} /></button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>)}<div className="nav-spacer" /><Tooltip><TooltipTrigger asChild><button className="avatar-button" aria-label="Account settings" onClick={() => setView("settings")}>C</button></TooltipTrigger><TooltipContent>Account settings</TooltipContent></Tooltip></nav><main className="content" aria-live="polite"><div className="mobile-heading"><span>{title}</span><span className="mobile-state">{state}</span></div>{state === "loading" ? <Loading /> : state !== "live" || !snapshot ? <Boundary state={state} onConnect={connect} /> : view === "overview" ? <Overview snapshot={snapshot} onNavigate={setView} /> : view === "usage" ? <Usage snapshot={snapshot} /> : view === "plans" ? <Plans snapshot={snapshot} onConnect={connect} /> : view === "status" ? <Status snapshot={snapshot} state={state} onConnect={connect} /> : <Settings topmost={topmost} onTopmost={(value) => { setTopmost(value); bridge.post({ action: "setting", value: { name: "topmost", enabled: value } }); }} onClear={() => bridge.post({ action: "clear" })} onConnect={connect} />}</main></div></div></TooltipProvider>;
}

function Loading() { return <div className="boundary loading-screen"><img src="./cavoti-logo.png" alt="" /><CircleNotch className="spin" size={22} /><h2>Loading Cavoti snapshot</h2><p>Waiting for the authenticated session bridge.</p></div>; }
function Boundary({ state, onConnect }: { state: BridgeState; onConnect: () => void }) { const copy = state === "offline" ? ["Cavoti is offline", "The authenticated profile could not reach Cavoti. Try again when the site is available."] : state === "error" ? ["The bridge needs attention", "The local host could not produce a safe snapshot."] : ["Live session required", "Sign in through the Cavoti connection window. Credentials stay in the native browser profile."]; return <div className="boundary"><div className="boundary-icon">{state === "auth-required" ? <LockKeyOpen /> : <WarningCircle />}</div><span className="eyebrow">{state === "auth-required" ? "Authentication" : "Connection"}</span><h2>{copy[0]}</h2><p>{copy[1]}</p><Button onClick={onConnect}>{state === "auth-required" ? "Connect Cavoti" : "Try again"} <ArrowSquareOut /></Button></div>; }
